E-Commerce/Controllers/SupCategoryController.cs
using Microsoft.AspNetCore.Mvc;
using ServiceLayer.services;
using ServiceLayer.ViewModels;
using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace E_Commerce.Controllers
{
    public class SupCategoryController : Controller
    {
        private readonly ISupCategoryServices _supCategoryServices;
        public SupCategoryController(ISupCategoryServices supCategoryServices)
        {
            _supCategoryServices = supCategoryServices;
        }
        public async Task< IActionResult> Index()
        {
            IEnumerable<SupCategoryViewModel> allsupcategory = await _supCategoryServices.GetAllSUpCategories(); 
            return View(allsupcategory);
        }

        public async Task<IActionResult> Create(SupCategoryViewModel newsupcategory)
        {
            if (ModelState.IsValid) { 
            await _supCategoryServices.AddSupCategory(newsupcategory);
                return RedirectToAction(nameof(Index));
            }
            return View("index", await _supCategoryServices.GetAllSUpCategories());
        }  
    }
}

E-Commerce/Views/SupCategory/Index.cshtml
@using ServiceLayer.ViewModels;
@model IEnumerable<SupCategoryViewModel>
<div class="table-responsive container-fluid">
    <table class="table   table-hover table-sm">
        <thead><tr><th>name</th> <th>delete</th></tr></thead>
   <tbody>
    @foreach (var item in Model)
   {
       <tr><td>@item.name</td> <td><a asp-action="Delete" asp-controller="SupCategory" asp-route-id="@item.id" class="btn btn-danger">Delete</a></td></tr>
   }
   </tbody>
    </table>
    </div>
    <div class="mb-3 bg-soft-info p-3  mt-2">
<partial name="_allcat"  model="new SupCategoryViewModel()"/>
</div>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

E-Commerce/Views/SupCategory/_allcat.cshtml
                                                   @*supcategory index*@
@using ServiceLayer.ViewModels;
@model SupCategoryViewModel

<form asp-action="create" asp-controller="SupCategory">
    <div class="form-group">
        <div class="row">
             <div class="col-3"><label asp-for="name"></label></div>
             <div class="col-6"><input asp-for="name" class="form-control"/></div>
              <span asp-validation-for="name" class="text-danger"></span>
             <div class="col-3"><input type="submit" value="add" class="btn btn-success"></div>

      </div>
       
    </div>
</form>